/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import cript.*;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.font.TextAttribute;
import java.io.File;
import java.util.Map;
import javax.swing.JFileChooser;

/**
 *
 * @author nanotech
 */
public class Form0 extends javax.swing.JFrame {

    Cript2010x8b program=null;
    Hash hash=null;
    String data="";
    public static Form0 singleton;
    public static boolean running=false;
    
    public static final boolean PRINT=true; 
    public static final boolean SAVEBKP=true; 
    
    public Form0() {
        initComponents();
        singleton=this;
        Thread.currentThread().setPriority(Thread.MIN_PRIORITY);
        Thread t1=new Thread() {
            @Override
            public void run() {
                while(true){
                    singleton.pb_run.setMaximum(Cript2010x8b.totalSteeps);
                    singleton.pb_run.setValue(Cript2010x8b.currentSteeps+Cript2010x8b.computingSteeps);
                    try{Thread.currentThread().sleep(200);}catch(Exception e){}
                }
            }
        };
        t1.setPriority(Thread.MIN_PRIORITY);
        t1.start();
        
        Thread t2=new Thread() {
            @Override
            public void run() {
                while(true){
                    if(running){
                        singleton.cbOK.setSelected(!singleton.cbOK.isSelected());
                    }else{
                        singleton.cbOK.setSelected(true);
                    }
                    try{Thread.currentThread().sleep(5);}catch(Exception e){}
                }
            }
        };
        t2.setPriority(Thread.MIN_PRIORITY);
        t2.start();
        this.setResizable(false);
        changeLanguage();
        jTextField2.setVisible(false);
        jTextField2.setEnabled(false);
        btn_loadTxtHash.setVisible(false);
        btn_loadTxtHash.setEnabled(false);
        if(this.cb_genRandHash.isSelected()){
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
        }else{
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
        }
        Font font = url.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        url.setFont(font.deriveFont(attributes));
        this.setTitle("Cript2010x8b");
        this.buttonGroup1.add(this.rb_cript);
        this.buttonGroup1.add(this.rb_decript);
        this.rb_cript.setSelected(true);
        url.setCursor(new Cursor(Cursor.HAND_CURSOR));
        url.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
                try{Desktop.getDesktop().browse(new URI(url.getText()));}
                catch (URISyntaxException | IOException ex) {}
            }
        });
        
        jTextField3.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            char key=e.getKeyChar();
            if (key<'0'| key>'9'){  e.consume(); }
        };
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb_cript = new javax.swing.JRadioButton();
        rb_decript = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btn_abrirhash = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cb_hashInFile = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        btn_loadTxtHash = new javax.swing.JButton();
        cb_genRandHash = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_openfile = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        btn_loadfromtext = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_log = new javax.swing.JTextArea();
        combo_language = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btn_run = new javax.swing.JLabel();
        pb_run = new javax.swing.JProgressBar();
        cbOK = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        url = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(171, 171, 171));

        rb_cript.setText("Cript");
        rb_cript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_criptActionPerformed(evt);
            }
        });

        rb_decript.setText("Decript");
        rb_decript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_decriptActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("MODE:");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("1");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("nCript");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_decript)
                    .addComponent(rb_cript)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(rb_cript)
                .addGap(12, 12, 12)
                .addComponent(rb_decript)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(171, 171, 171));

        jTextField1.setEditable(false);

        btn_abrirhash.setText("Abrir");
        btn_abrirhash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrirhashActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Hash:");

        cb_hashInFile.setSelected(true);
        cb_hashInFile.setText("Hash no arquivo");
        cb_hashInFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hashInFileActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        btn_loadTxtHash.setText("Via Texto");
        btn_loadTxtHash.setEnabled(false);
        btn_loadTxtHash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_loadTxtHashMouseReleased(evt);
            }
        });
        btn_loadTxtHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadTxtHashActionPerformed(evt);
            }
        });

        cb_genRandHash.setSelected(true);
        cb_genRandHash.setText("Gerar hash randomico");
        cb_genRandHash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cb_genRandHashMouseReleased(evt);
            }
        });
        cb_genRandHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_genRandHashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_hashInFile)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btn_loadTxtHash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_abrirhash))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_genRandHash)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_abrirhash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_hashInFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_loadTxtHash))
                .addGap(7, 7, 7)
                .addComponent(cb_genRandHash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(171, 171, 171));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("File:");

        btn_openfile.setText("Abrir");
        btn_openfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_openfileMouseReleased(evt);
            }
        });
        btn_openfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openfileActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        btn_loadfromtext.setText("Carregar");
        btn_loadfromtext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_loadfromtextMouseReleased(evt);
            }
        });
        btn_loadfromtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadfromtextActionPerformed(evt);
            }
        });

        jLabel9.setText("log:");

        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setWheelScrollingEnabled(false);

        txt_log.setColumns(20);
        txt_log.setRows(1);
        jScrollPane1.setViewportView(txt_log);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField4)
                .addGap(0, 0, 0)
                .addComponent(btn_openfile))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_loadfromtext))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_openfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_loadfromtext)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(35, 35, 35))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
        );

        combo_language.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portugues", "English" }));
        combo_language.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_languagePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combo_language.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                combo_languageMouseReleased(evt);
            }
        });
        combo_language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_languageActionPerformed(evt);
            }
        });
        combo_language.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                combo_languagePropertyChange(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(171, 171, 171));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setPreferredSize(new java.awt.Dimension(590, 21));

        btn_run.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_run.setText("jLabel5");
        btn_run.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, pb_run, org.jdesktop.beansbinding.ObjectProperty.create(), btn_run, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        btn_run.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_runMouseReleased(evt);
            }
        });

        pb_run.setValue(100);
        pb_run.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pb_runMouseReleased(evt);
            }
        });

        cbOK.setText("OK");
        cbOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbOKMouseReleased(evt);
            }
        });
        cbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_run, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(pb_run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(162, 162, 162)
                .addComponent(cbOK))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_run, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pb_run, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(cbOK))
        );

        jPanel5.setBackground(new java.awt.Color(171, 171, 171));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Cript2010x8b");

        jLabel7.setText("by: nanoTech");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(141, 141, 141)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)))
        );

        url.setForeground(new java.awt.Color(64, 0, 255));
        url.setText("https://github.com/thiagofigcosta/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(url)
                .addGap(206, 206, 206)
                .addComponent(combo_language, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(url))
                    .addComponent(combo_language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_criptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_criptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_criptActionPerformed

    private void rb_decriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_decriptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_decriptActionPerformed

    private void btn_abrirhashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrirhashActionPerformed
        try{
            JFileChooser openFile = new JFileChooser();
            if (openFile.showOpenDialog(jPanel1) == JFileChooser.APPROVE_OPTION) {
                this.cb_genRandHash.setSelected(false);
                this.jTextField1.setText(openFile.getSelectedFile().getPath()); 
                this.hash=new Hash(IO.readFileAsString(openFile.getSelectedFile().getPath()));
            }
        }catch(Exception e){
            this.txt_log.setText(this.txt_log.getText()+e+"\n");
        }
    }//GEN-LAST:event_btn_abrirhashActionPerformed

    private void cb_hashInFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hashInFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_hashInFileActionPerformed

    private void btn_loadTxtHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadTxtHashActionPerformed
        
    }//GEN-LAST:event_btn_loadTxtHashActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cb_genRandHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_genRandHashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_genRandHashActionPerformed

    private void combo_languageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_languageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_languageActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void combo_languageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_languageMouseReleased
        
    }//GEN-LAST:event_combo_languageMouseReleased

    private void combo_languagePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_combo_languagePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_languagePropertyChange

    private void combo_languagePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_languagePopupMenuWillBecomeInvisible
        changeLanguage();
    }//GEN-LAST:event_combo_languagePopupMenuWillBecomeInvisible

    private void cb_genRandHashMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_genRandHashMouseReleased
        if(this.cb_genRandHash.isSelected()){
            jTextField1.setText("");
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
        }else{
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
        }
    }//GEN-LAST:event_cb_genRandHashMouseReleased

    private void btn_loadTxtHashMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loadTxtHashMouseReleased
        try{
            hash=new Hash(this.jTextField2.getText());
        }catch(Exception e){
            this.txt_log.setText(this.txt_log.getText()+e+"\n");
        }
    }//GEN-LAST:event_btn_loadTxtHashMouseReleased

    private void btn_loadfromtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadfromtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loadfromtextActionPerformed

    private void btn_loadfromtextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loadfromtextMouseReleased
        this.data=this.jTextField5.getText();
    }//GEN-LAST:event_btn_loadfromtextMouseReleased

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void btn_openfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openfileActionPerformed

    }//GEN-LAST:event_btn_openfileActionPerformed

    private void btn_openfileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_openfileMouseReleased
        this.data="";
        String path="";
        try{
            JFileChooser openFile = new JFileChooser();
            if (openFile.showOpenDialog(jPanel1) == JFileChooser.APPROVE_OPTION) {
                this.jTextField4.setText(openFile.getSelectedFile().getPath());
                path=openFile.getSelectedFile().getPath();
                this.data=IO.readFileAsString(openFile.getSelectedFile().getPath());
            }
        }catch(Exception e){
            this.txt_log.setText(this.txt_log.getText()+e+"\n");
        }
        if(SAVEBKP&&!"".equals(path)&&this.rb_cript.isSelected()){
            try{
                IO.saveFile(data, path+"BKP");
            }catch(Exception e){}
        }
    }//GEN-LAST:event_btn_openfileMouseReleased

    private void cbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOKActionPerformed
         if (cbOK.isSelected())
            cbOK.setSelected(false);
        else
            cbOK.setSelected(true);
    }//GEN-LAST:event_cbOKActionPerformed

    private void cbOKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbOKMouseReleased
       
    }//GEN-LAST:event_cbOKMouseReleased

    private void pb_runMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pb_runMouseReleased
        btnrun();
    }//GEN-LAST:event_pb_runMouseReleased

    private void btn_runMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_runMouseReleased
        btnrun();
    }//GEN-LAST:event_btn_runMouseReleased

    private void changeLanguage(){
        if(this.combo_language.getSelectedIndex()==0){//PT
            this.cb_hashInFile.setText("Chave no arquivo");
            this.cb_genRandHash.setText("Gerar chave aleatoria");
            this.btn_abrirhash.setText("Abrir");
            this.btn_loadTxtHash.setText("Via texto");
            this.btn_openfile.setText("Abrir");
            this.btn_loadfromtext.setText("Via  texto");
            this.jLabel2.setText("Chave:");
            this.jLabel1.setText("Modo:");
            this.jLabel3.setText("Arquivo:");
            this.jLabel3.setText("Arquivo:");
            this.btn_run.setText("Rodar");
        }else if(this.combo_language.getSelectedIndex()==1){//EN
            this.cb_hashInFile.setText("Hash in file");
            this.cb_genRandHash.setText("Gen random hash");
            this.btn_abrirhash.setText("Open");
            this.btn_loadTxtHash.setText("From text");
            this.btn_openfile.setText("Open");
            this.btn_loadfromtext.setText("Load from text");
            this.jLabel2.setText("Hash:");
            this.jLabel1.setText("Mode:");
            this.jLabel3.setText("File:");
            this.jLabel3.setText("File:");
            this.btn_run.setText("Run");
        }
    }
    
    private void btnrun(){
        if(running)return;
        running=true;
        Thread x=new Thread() {
            @Override
            public void run() {
                if(singleton.cb_genRandHash.isSelected()){
                    hash=Hash.genRandom();
                }
                if("".equals(data)){
                    singleton.txt_log.setText(singleton.txt_log.getText()+"missing data"+"\n");
                }else
                if(hash!=null){
                    program=null;
                    try{
                        program=new Cript2010x8b(Integer.valueOf(singleton.jTextField3.getText()),singleton.rb_cript.isSelected(),hash,data,singleton.cb_hashInFile.isSelected()); 
                        if(singleton.rb_cript.isSelected()){
                            if(singleton.combo_language.getSelectedIndex()==0){
                                singleton.txt_log.setText(singleton.txt_log.getText()+"Criptografado: "+program.percetage+"%\n");
                            }else{
                                singleton.txt_log.setText(singleton.txt_log.getText()+"Cripted: "+program.percetage+"%\n");
                            }
                        }else{
                             if(singleton.combo_language.getSelectedIndex()==0){
                                singleton.txt_log.setText(singleton.txt_log.getText()+"Descriptografado!"+"\n");
                            }else{
                                singleton.txt_log.setText(singleton.txt_log.getText()+"Decripted!"+"\n");
                            }
                        }
                        JFileChooser saveFile=null;
                        try{
                            saveFile = new JFileChooser();
                            try{saveFile.setSelectedFile(new File(singleton.jTextField4.getText()));}catch(Exception e){}
                            if (saveFile.showSaveDialog(jPanel1) == JFileChooser.APPROVE_OPTION) {
                                IO.saveFile(program.getData(),saveFile.getSelectedFile().getAbsolutePath());
                        }
                        }catch(Exception e){
                            singleton.txt_log.setText(singleton.txt_log.getText()+e+"\n");
                        }
                        if(!singleton.cb_hashInFile.isSelected()&&singleton.rb_cript.isSelected()){
                            try{
                                String ext="";
                                String filename=saveFile.getSelectedFile().getName();
                                for(int i=0;i<filename.length();i++){
                                    if(filename.charAt(i)=='.'){
                                        filename=filename.substring(0, i);
                                        ext=filename.substring(i);
                                        break;
                                    }
                                }
                                IO.saveFile(hash.compressHash(), saveFile.getSelectedFile().getAbsolutePath().replace(filename, filename+"-hash("+singleton.jTextField3.getText()+")"));//+ext));
                            }catch(Exception e){
                                singleton.txt_log.setText(singleton.txt_log.getText()+e+"\n");
                            }
                        }
                    }catch(Exception e){
                        singleton.txt_log.setText(singleton.txt_log.getText()+e+"\n");
                    }
                }else{
                    singleton.txt_log.setText(singleton.txt_log.getText()+"missing hash"+"\n");
                }
                data="";
                Cript2010x8b.totalSteeps=1;
                Cript2010x8b.currentSteeps=0;
                Cript2010x8b.computingSteeps=1;
                running=false;
            }
        };
        x.setPriority(Thread.MAX_PRIORITY);
        x.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abrirhash;
    private javax.swing.JButton btn_loadTxtHash;
    private javax.swing.JButton btn_loadfromtext;
    private javax.swing.JButton btn_openfile;
    private javax.swing.JLabel btn_run;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbOK;
    private javax.swing.JCheckBox cb_genRandHash;
    private javax.swing.JCheckBox cb_hashInFile;
    private javax.swing.JComboBox<String> combo_language;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JProgressBar pb_run;
    private javax.swing.JRadioButton rb_cript;
    private javax.swing.JRadioButton rb_decript;
    private javax.swing.JTextArea txt_log;
    private javax.swing.JLabel url;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
